board: 6x CNC Controller
name: 6x Default

# # global stepping settings
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 14.14710605
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 500.000
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 3.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: gpio.2:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1:low
        disable_pin: I2SO.0
  y:
    steps_per_mm: 14.14710605
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 800.000
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 3.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.26:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4:high
        disable_pin: I2SO.7

    motor1:
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9:high
        disable_pin: I2SO.8

  z:
    steps_per_mm: 990.4761905
    max_rate_mm_per_min: 400.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 95.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 3.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12:low
        disable_pin: I2SO.15

# a and b commented out
#  a:
#    steps_per_mm: 53.400
#    max_rate_mm_per_min: 800.000
#    acceleration_mm_per_sec2: 100.000
#    max_travel_mm: 960.000
#    soft_limits: false
#    homing:
#      cycle: 2
#      positive_direction: false
#      mpos_mm: 150.000
#      feed_mm_per_min: 100.000
#      seek_mm_per_min: 200.000
#      settle_ms: 500
#      seek_scaler: 1.100
#      feed_scaler: 1.100

#    motor0:
#      limit_neg_pin: NO_PIN
#      limit_pos_pin: NO_PIN
#      limit_all_pin: NO_PIN
#      hard_limits: false
#      pulloff_mm: 5.000
#      standard_stepper:
#        step_pin: I2SO.18
#        direction_pin: I2SO.17
#        disable_pin: I2SO.16
#
#  b:
#    steps_per_mm: 808.000
#    max_rate_mm_per_min: 800.000
#    acceleration_mm_per_sec2: 100.000
#    max_travel_mm: 200.000
#    soft_limits: false
#    homing:
#      cycle: 1
#      positive_direction: false
#      mpos_mm: 150.000
#      feed_mm_per_min: 100.000
#      seek_mm_per_min: 200.000
#      settle_ms: 500
#      seek_scaler: 1.100
#      feed_scaler: 1.100
#
#    motor0:
#      limit_neg_pin: NO_PIN
#      limit_pos_pin: NO_PIN
#      limit_all_pin: NO_PIN
#      hard_limits: false
#      pulloff_mm: 5.000
#      standard_stepper:
#        step_pin: I2SO.21
#        direction_pin: I2SO.20
#        disable_pin: I2SO.23

relay:
  direction_pin: NO_PIN
  output_pin: gpio.12:low:pu
  enable_pin: NO_PIN
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 0=100.000% 1=100.000%
  off_on_alarm: true

user_outputs:
  digital0_pin: gpio.14:high:pd
  digital1_pin: gpio.13:low:pu
  digital2_pin: gpio.4:low:pu

control:
  feed_hold_pin: gpio.34:low:pu
  safety_door_pin: gpio.39:low:pu
  reset_pin: gpio.36:low:pu


i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

start:
  must_home: false
